<!DOCTYPE html>
<html>
<head>
    <title>Test Email</title>
</head>
<body>
    <h2>Test Email from Treasury App</h2>
    <p>This is a test email sent at {{ now()->format('Y-m-d H:i:s') }}</p>
    <p>If you receive this email, the Gmail SMTP configuration is working correctly.</p>
    <hr>
    <p><small>Generated by Laravel Mail System</small></p>
</body>
</html>
